version: '2'
services:
  mqtt:
    image: ansi/mosquitto
    container_name: c-beam
    ports:
      - '1883:1883'
    entrypoint: /usr/local/sbin/mosquitto
  msgflo:
    image: cbase/c3-flo
    container_name: c3-flo
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    ports:
      - '3569:3569'
    links:
      - mqtt
  msgflo_foreign:
    image: cbase/c3-flo
    container_name: c3-flo-foreign
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    links:
      - mqtt
    entrypoint: npm run foreign
