version: '2'
services:
  mqtt:
    image: toke/mosquitto
    ports:
      - '1882:9001'
      - '1883:1883'
  msgflo:
    image: cbase/c3-flo
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
      INFOSCREENS_URL: 'http://localhost'
    ports:
      - '3569:3569'
    links:
      - mqtt
    volumes:
      - ./graphs:/var/c3-flo/graphs
      - ./components:/var/c3-flo/components
      - ./spec:/var/c3-flo/spec
  msgflo_foreign:
    image: cbase/c3-flo
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    links:
      - mqtt
      - msgflo
    entrypoint: npm run foreign
    volumes:
      - ./components:/var/c3-flo/components
  announcer:
    image: cbase/station-announcer
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    links:
      - mqtt
  infoscreens:
    image: cbase/infoscreens
    ports:
      - '80:80'
    links:
      - mqtt
  influxdb:
    image: influxdb
    ports:
      - '127.0.0.1:8086:8086'
  couchdb:
    image: couchdb
    ports:
      - '5984:5984'
  openmct:
    image: cbase/cbeam-telemetry-server
    entrypoint: node config/c3-flo.js
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
      INFLUX_HOST: influxdb
    ports:
      - '8080:8080'
      - '8082:8082'
    links:
      - influxdb
      - couchdb
      - mqtt
    volumes:
      - ./openmct:/var/cbeam-telemetry-server/config
