version: '2'
services:
  mqtt:
    image: toke/mosquitto
    container_name: c-beam
    ports:
      - '1882:9001'
      - '1883:1883'
  msgflo:
    image: cbase/c3-flo
    container_name: c3-flo
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    ports:
      - '3569:3569'
    links:
      - mqtt
    volumes:
      - ./graphs:/var/c3-flo/graphs
      - ./components:/var/c3-flo/components
      - ./spec:/var/c3-flo/spec
  msgflo_foreign:
    image: cbase/c3-flo
    container_name: c3-flo-foreign
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    links:
      - mqtt
    entrypoint: npm run foreign
    volumes:
      - ./components:/var/c3-flo/components
  announcer:
    image: cbase/station-announcer
    container_name: station-announcer
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    links:
      - mqtt
  infoscreens:
    image: cbase/infoscreens
    ports:
      - '80:80'
    links:
      - mqtt-infoscreens
